### ISSUE TITLE
Exception TargetInvocationException in GitTags(..)

### ISSUE THREAD

**Issue by andrewst** [cake-contrib/Cake_Git#56]
Hi, 
I get exception TargetInvocationException in GitTags(".");
I using Windows 10 x64,  Cake.0.25.0, Cake.Git.0.16.1.

`
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at LibGit2Sharp.Core.NativeMethods.git_object_lookup(git_object*& obj, git_repository* repo, GitOid& id, GitObjectType type)
   at LibGit2Sharp.Core.Proxy.git_object_lookup(RepositoryHandle repo, ObjectId id, GitObjectType type) in C:\git\libgit2sharp\LibGit2Sharp.Shared\Core\Proxy.cs:line 1455
   at LibGit2Sharp.Repository.LookupInternal(ObjectId id, GitObjectType type, FilePath knownPath) in C:\git\libgit2sharp\LibGit2Sharp.Shared\Repository.cs:line 532
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LibGit2Sharp.ReferenceWrapper`1.RetrieveTargetObject(Reference reference) in C:\git\libgit2sharp\LibGit2Sharp.Shared\ReferenceWrapper.cs:line 107
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LibGit2Sharp.Tag.get_Annotation() in C:\git\libgit2sharp\LibGit2Sharp.Shared\Tag.cs:line 24
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.SecurityUtils.MethodInfoInvoke(MethodInfo method, Object target, Object[] args)
   at System.ComponentModel.ReflectPropertyDescriptor.GetValue(Object component)
   at Cake.Incubator.LoggingExtensions.ObjectToString[T](T obj) in C:\projects\cake-incubator\src\Cake.Incubator\LoggingExtensions.cs:line 86
   at Cake.Incubator.LoggingExtensions.Dump[T](T obj) in C:\projects\cake-incubator\src\Cake.Incubator\LoggingExtensions.cs:line 70
   at Submission#0.<<Initialize>>b__0_0(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.PerformSetup(Action`1 action, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 44
   at Cake.Core.CakeEngine.PerformSetup(IExecutionStrategy strategy, ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 209
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext() in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 135
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext() in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 44
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 173
   at Submission#0.<<Initialize>>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Submission#0.<Initialize>()
   at Submission#0.<Factory>(Object[] submissionArray)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 127
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 212
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 35
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 74`

**Comment by pascalberger** [comment]
Fixed with #129
