### ISSUE TITLE
Issue with accessing Tag properties

### ISSUE THREAD

**Issue by joepour** [cake-contrib/Cake_Git#72]
Hey @devlead,

When I try and get tags using the following: 

```
    #addin "nuget:?package=Cake.Git"

    var tags = GitTags(DirectoryPath.FromString("../"));
```
I get a list of tags, but when I try and access the `.Target` property

```
Information($"The version of this project is {packageVersion} - {tag.FriendlyName} - {tag.Reference} - {tag.Target}");
```
I get the following exception:

```
Cake.exe : 
At C:\ClickView Projects\HomeMigrator\build\build.ps1:235 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Unhandled Exception: 
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at LibGit2Sharp.Core.NativeMethods.git_object_lookup(git_object*& obj, git_repository* repo, GitOid& id, GitObjectType type)
   at LibGit2Sharp.Core.Proxy.git_object_lookup(RepositoryHandle repo, ObjectId id, GitObjectType type) in C:\git\libgit2sharp\LibGit2Sharp.Shared\Core\Proxy.cs:line 1455
   at LibGit2Sharp.Repository.LookupInternal(ObjectId id, GitObjectType type, FilePath knownPath) in C:\git\libgit2sharp\LibGit2Sharp.Shared\Repository.cs:line 532
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LibGit2Sharp.ReferenceWrapper`1.RetrieveTargetObject(Reference reference) in C:\git\libgit2sharp\LibGit2Sharp.Shared\ReferenceWrapper.cs:line 107
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LibGit2Sharp.Tag.get_Target() in C:\git\libgit2sharp\LibGit2Sharp.Shared\Tag.cs:line 34
   at Submission#0.<<Initialize>>b__0_2()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Core.CakeTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report)
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Submission#0.<Initialize>()
   at Submission#0.<Factory>(Object[] submissionArray)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 
exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, 
Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object
 globals, Func`2 catchException, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```
Am I doing somethign wrong or this a bug? I am running the latest from nuget (0.18.0). Really appreciate all the great work on this project, thanks in advance!

**Comment by Harllens** [comment]
Do anyone has a workaround for this issue?

**Comment by joepour** [comment]
Hey @Harllens, 

This is how I solved it for us:

```
#addin nuget:?package=Cake.FileHelpers&version=3.2.0
#addin nuget:?package=Cake.Git&version=0.19.0
#load  common/constants.cake

var packageVersion = ProjectConstants.DefaultPackageVersion;
var isRelease            = Argument<bool>("IsRelease", false);

Task("Version")
    .Does(() => {
        var dir          = DirectoryPath.FromString("../");
        var branch   = GitBranchCurrent(dir).FriendlyName;
        var commit  = GitLogTip(dir).Sha.Substring(0, 8);

        // Remove unsafe chars
        branch = System.Text.RegularExpressions.Regex.Replace(branch, @"[\\/_]+", @"-");

        if(branch.Equals("master", StringComparison.OrdinalIgnoreCase))
        {
            isRelease = true;
            packageVersion = FileReadText(ProjectConstants.VersionPath);
        }
        else
        {
            packageVersion = $"0.0.0-{branch}+{commit}";
        }

        Information($"The version of this project is {packageVersion}");
    });
```

**Comment by lbensch** [comment]
Hello,

The problem still exists and I have no other solution to get the list of tags. Is a correction planned?
